repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4  # Use the latest version
    hooks:
      - id: ruff
        args: ["--fix", "django_backend", "django_project"]  # Specify directories to check
      - id: ruff-format
        args: ["django_backend", "django_project"]  # Specify directories to check
