# Generated by Django 5.1 on 2025-04-01 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manhwa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("en_title", models.CharField(blank=True, max_length=512)),
                ("en_description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(blank=True, upload_to="")),
                ("mangadex_id", models.CharField(blank=True, max_length=512)),
                ("toonkor_id", models.SlugField(unique=True)),
                ("in_library", models.BooleanField(default=True)),
                ("last_update", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ToonkorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("url", models.URLField(default="https://tkor08.com")),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("toonkor_id", models.SlugField(unique=True)),
                ("date_upload", models.CharField(blank=True, max_length=512)),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("NOT_READY", "Not Ready"),
                            ("LOADING", "Loading"),
                            ("READY", "Ready"),
                            ("REMOVING", "Removing"),
                        ],
                        default="NOT_READY",
                        max_length=20,
                    ),
                ),
                (
                    "translation_status",
                    models.CharField(
                        choices=[
                            ("NOT_READY", "Not Ready"),
                            ("LOADING", "Loading"),
                            ("READY", "Ready"),
                            ("REMOVING", "Removing"),
                        ],
                        default="NOT_READY",
                        max_length=20,
                    ),
                ),
                (
                    "manhwa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.manhwa",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
    ]
