# Generated by Django 5.1 on 2025-04-01 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["index"]},
        ),
    ]
