# Generated by Django 5.1 on 2025-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toonkorsettings",
            name="url",
        ),
        migrations.AddField(
            model_name="toonkorsettings",
            name="curl_command",
            field=models.TextField(
                blank=True,
                default="curl 'https://tkor08.com/%EC%9B%B9%ED%88%B0' --compressed -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0'",
            ),
        ),
        migrations.AlterField(
            model_name="toonkorsettings",
            name="name",
            field=models.CharField(max_length=8),
        ),
    ]
