# Generated by Django 5.1 on 2025-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0002_remove_toonkorsettings_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toonkorsettings",
            name="translation_page_limit",
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name="toonkorsettings",
            name="curl_command",
            field=models.TextField(
                blank=True,
                default="curl 'https://tkor08.com' --compressed -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0'",
            ),
        ),
    ]
