# Generated by Django 5.1 on 2025-04-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0003_toonkorsettings_translation_page_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toonkorsettings",
            name="translation_page_limit",
            field=models.PositiveSmallIntegerField(default=999),
        ),
    ]
