# Generated by Django 5.1 on 2025-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0004_alter_toonkorsettings_translation_page_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="last_edit",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
